export const CHANGE_CATE = 'PRODUCT/CHANGE_CATE'
export const GET_PRODUCTS = 'PRODUCT/GET_PRODUCTS'
export const UPDATE_PRODUCT_LIST = 'UPDATE_PRODUCT_LIST'
export const PUSH_PRODUCT_LIST = 'PUSH_PRODUCT_LIST'
